NAME = cool_sed

SRC = main.cpp Config.cpp

CXX = c++
CXXFLAGS = -Wall -Wextra
CXXFLAGS += -g3
# CXXFLAGS += -Werror
CXXFLAGS += -std=c++98

CPPFLAGS = -I.

.dick: build clean run log
build: $(NAME)

run: build
	./$(NAME)

log: build
	./$(NAME) >log

$(NAME): $(SRC)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(SRC) -o $(NAME)

clean:
	rm -rf $(NAME)

.dick: b r
b: build
r: run
