name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: configure
      run: cmake -B build -G Ninja
      
    - name: build
      run: cmake --build build

    - name: install dependencies
      run: sudo apt-get update && sudo apt-get -y install valgrind

    - name: run memcheck
      run: valgrind ./build/module04/ex03/materias
